import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const arr = [
	{
		id: 1,
		name: 'Deep Learning: An Intro',
		description: 'This blog discusses about intro to Deep Learning'
	},
	{
		id: 2,
		name: 'Deep Learning: Past',
		description: 'This blog discusses about Past of Deep Learning'
	},
	{
		id: 3,
		name: 'Deep Learning: Present',
		description: 'This blog discusses about Present of Deep Learning'
	},
	{
		id: 4,
		name: 'Deep Learning: Future',
		description: 'This blog discusses about Future of Deep Learning'
	}
] 

export default function Home() {
  return (
	<>
	  <Head>
		<title>Create Next App</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/favicon.ico" />
	  </Head>
	  <main className={styles.main}>
		<div>
			<h2>Welcome to the Blog-AI</h2>
		</div>
		<ul className={styles.list}>
			{arr.map(el => (
				<li key={el.id}>
					<div>
						<p>{el.name}</p>
						<p>{el.description}</p>
						<p>{new Date().toString()}</p>
					</div>
				</li>
				)
			)}
		</ul>
	  </main>

	</>
  )
}
